### ISSUE TITLE
Any interest in alternative output schemes?

### ISSUE THREAD

**Issue by kalafut** [tylerb/is#2]
I like the leanness of this library a lot. But I'm using it in a terminal application that takes over the screen, so I forked your repo to hack in a way to buffer the test result outputs so I could see them. I don't like being on a fork for this, especially when I'm changing _other_ libraries and want to use 'is'.

I assume you're trying to keep this really small, but any interest in supporting some optional message buffering or logging? The change is pretty minor. Right now my fork is rough, just getting something to work for my project. If you wanted this additional feature, I'd be happy to clean things up (probably to just take a Writer as an output) and submit a pull request. If not, that's fine too.

**Comment by tylerb** [comment]
Glad you like it!



It's not a bad idea, but I am wondering if you thought of redirecting the stdout/stderr to a file? Is that not possible in your scenario?

**Comment by kalafut** [comment]
That's actually where I started. But termbox completely seizes the console, plus I have to contend with Windows use as well. I didn't find a good way to leverage redirection.

BTW, I just replaced my fork with simple Writer-based implementation that is cleaner than the string I was using if you happened to look about 10 minutes ago...

**Comment by tylerb** [comment]
I haven't been at my computer so I haven't had a chance to look. I'll get back to you when I am able.

**Comment by tylerb** [comment]
Your fork looks good to me. Straightforward and clean. Very nice.
